# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

image: jackfirth/racket:6.8

pipelines:
  default:
    - step:
        script:
          - raco pkg install --auto compiler-lib typed-racket-lib
          - find . -name "*.rkt" | xargs raco make -v